### ISSUE TITLE
Random GeneralFailure error

### ISSUE THREAD

**Issue by quentinlesceller** [ark0f/hyper-socks2#3]
Hi, first of all thank you very much for writing this Hyper connector.

For some reasons the `no_auth*` tests are randomly failing.
```
/hyper-socks2 master*
❯ cargo test --release http_no_auth
    Finished release [optimized] target(s) in 0.08s
     Running target/release/deps/hyper_socks2-4c1bce98cec5d7b5

running 2 tests
test tests::http_no_auth ... ok
test tests::http_no_auth_swap ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out


~/hyper-socks2 master*
❯ cargo test --release http_no_auth
    Finished release [optimized] target(s) in 0.10s
     Running target/release/deps/hyper_socks2-4c1bce98cec5d7b5

running 2 tests
test tests::http_no_auth ... ok
test tests::http_no_auth_swap ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out


~/hyper-socks2 master*
❯ cargo test --release http_no_auth
    Finished release [optimized] target(s) in 0.08s
     Running target/release/deps/hyper_socks2-4c1bce98cec5d7b5

running 2 tests
test tests::http_no_auth ... FAILED
test tests::http_no_auth_swap ... FAILED

failures:

---- tests::http_no_auth stdout ----
thread 'tests::http_no_auth' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, Socks(Response(GeneralFailure)))', src/lib.rs:239:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::http_no_auth_swap stdout ----
thread 'tests::http_no_auth_swap' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, Socks(Response(GeneralFailure)))', src/lib.rs:239:21


failures:
    tests::http_no_auth
    tests::http_no_auth_swap

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 6 filtered out

error: test failed, to rerun pass '--lib'

~/hyper-socks2 master*
```

**Comment by yeastplume** [comment]
Can confirm, the connector only works occasionally, usually fails. The `connect_no_auth` test in `async-socks5` appear to work consistently, so it would seem there is something odd happening within the hyper connector itself or above.

**Comment by yeastplume** [comment]
Tor logs from a successful run using the `connect_no_auth` test in the `async-socks5` crate, this is after writing the domain and port during a request:
```
May 29 12:01:12.000 [debug] connection_ap_handshake_process_socks(): socks handshake not all here yet.
May 29 12:01:12.000 [debug] conn_write_callback(): socket 10 wants to write.
May 29 12:01:12.000 [debug] conn_read_callback(): socket 10 wants to read.
May 29 12:01:12.000 [debug] read_to_chunk(): Read 17 bytes. 17 on inbuf.
May 29 12:01:12.000 [debug] connection_ap_handshake_process_socks(): entered.
May 29 12:01:12.000 [debug] connection_ap_handshake_rewrite(): Client asked for google.com:80
... circuit negotiation, followed by
ay 29 12:01:12.000 [debug] connection_or_process_cells_from_inbuf(): 9: starting, inbuf_datalen 0 (0 pending in tls object).
May 29 12:01:12.000 [debug] conn_write_callback(): socket 10 wants to write.
May 29 12:01:12.000 [debug] conn_read_callback(): socket 10 wants to read.
```

Now from an unsuccessful run using the `http_no_auth` test in the `hyper-socks2` crate:

```
May 29 12:01:25.000 [debug] connection_ap_handshake_process_socks(): socks handshake not all here yet.
May 29 12:01:25.000 [debug] conn_write_callback(): socket 10 wants to write.
May 29 12:01:25.000 [debug] conn_read_callback(): socket 10 wants to read.
May 29 12:01:25.000 [debug] read_to_chunk(): Read 2 bytes. 17 on inbuf.
May 29 12:01:25.000 [debug] connection_ap_handshake_process_socks(): entered.
May 29 12:01:25.000 [debug] connection_ap_handshake_rewrite(): Client asked for google.com:80
May 29 12:01:25.000 [info] add_predicted_port(): New port prediction added. Will continue predictive circ building for 2319 more seconds.
.. circuit negotiation, but then
May 29 12:01:25.000 [debug] conn_read_callback(): socket 10 wants to read.
May 29 12:01:25.000 [debug] connection_edge_end(): Sending end on conn (fd 10).
```

This is suggesting that the SocksConnector is sending data when it's not expected to, before receiving a response. The server then drops the connection with a general failure.

Also, I do notice that when I add some trace statements and turn logging on, the `http_no_auth` test will never succeed, suggesting some sort of timing issue between the last bytes of the request being sent and the unexpected byte the server sends; if the client writes quickly enough and the server responds before the client tries to write the rogue bytes, the call succeeds.
